### ISSUE TITLE
Property Opened is showing error

### ISSUE THREAD

**Issue by nahid1991** [jkuri/ng2-datepicker#106]
This is what I am using in my HTML:
`<ng2-datepicker [opened]="true" [(ngModel)]="date" [ngModelOptions]="{standalone: true}"></ng2-datepicker>`

Error in console shown:
```
zone.js:388Unhandled Promise rejection: Template parse errors:
Can't bind to 'opened' since it isn't a known property of 'ng2-datepicker'.
1. If 'ng2-datepicker' is an Angular component and it has 'opened' input, then verify that it is part of this module.
2. If 'ng2-datepicker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("         <div class="input-group date">
              <label>DATE OF BIRTH: </label><ng2-datepicker [ERROR ->][opened]="true" [(ngModel)]="date" [ngModelOptions]="{standalone: true}"></ng2-datepicker>
          "): AuthmodalsComponent@27:60 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Can't bind to 'opened' since it isn't a known property of 'ng2-datepicker'.
1. If 'ng2-datepicker' is an Angular component and it has 'opened' input, then verify that it is part of this module.
2. If 'ng2-datepicker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("         <div class="input-group date">
              <label>DATE OF BIRTH: </label><ng2-datepicker [ERROR ->][opened]="true" [(ngModel)]="date" [ngModelOptions]="{standalone: true}"></ng2-datepicker>
          "): AuthmodalsComponent@27:60
    at TemplateParser.parse (http://localhost:4200/main.bundle.js:16914:19)
    at RuntimeCompiler._compileTemplate (http://localhost:4200/main.bundle.js:37505:51)
    at http://localhost:4200/main.bundle.js:37410:83
    at Set.forEach (native)
    at compile (http://localhost:4200/main.bundle.js:37410:47)
    at ZoneDelegate.invoke (http://localhost:4200/main.bundle.js:78309:26)
    at Zone.run (http://localhost:4200/main.bundle.js:78191:43)
    at http://localhost:4200/main.bundle.js:78579:57
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:78342:35)
    at Zone.runTask (http://localhost:4200/main.bundle.js:78231:47)zone.js:388Unhandled Promise rejection: Template parse errors:
Can't bind to 'opened' since it isn't a known property of 'ng2-datepicker'.
1. If 'ng2-datepicker' is an Angular component and it has 'opened' input, then verify that it is part of this module.
2. If 'ng2-datepicker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("         <div class="input-group date">
              <label>DATE OF BIRTH: </label><ng2-datepicker [ERROR ->][opened]="true" [(ngModel)]="date" [ngModelOptions]="{standalone: true}"></ng2-datepicker>
          "): AuthmodalsComponent@27:60 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
Can't bind to 'opened' since it isn't a known property of 'ng2-datepicker'.
1. If 'ng2-datepicker' is an Angular component and it has 'opened' input, then verify that it is part of this module.
2. If 'ng2-datepicker' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("         <div class="input-group date">
              <label>DATE OF BIRTH: </label><ng2-datepicker [ERROR ->][opened]="true" [(ngModel)]="date" [ngModelOptions]="{standalone: true}"></ng2-datepicker>
          "): AuthmodalsComponent@27:60
    at TemplateParser.parse (http://localhost:4200/main.bundle.js:16914:19)
    at RuntimeCompiler._compileTemplate (http://localhost:4200/main.bundle.js:37505:51)
    at http://localhost:4200/main.bundle.js:37410:83
    at Set.forEach (native)
    at compile (http://localhost:4200/main.bundle.js:37410:47)
    at ZoneDelegate.invoke (http://localhost:4200/main.bundle.js:78309:26)
    at Zone.run (http://localhost:4200/main.bundle.js:78191:43)
    at http://localhost:4200/main.bundle.js:78579:57
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:78342:35)
    at Zone.runTask (http://localhost:4200/main.bundle.js:78231:47)
```
Without the property binding everything works. But I actually need the default calendar shown option.

**Comment by przennek** [comment]
Any updates?
