### ISSUE TITLE
HELP! Import success but failed to load resource

### ISSUE THREAD

**Issue by 2353551096** [jkuri/ng2-datepicker#133]
I have installed ng2-datepicker via npm and include Ionicons's CSS in index.html  
then i have done with optionA,but there have some ERROR ：

Failed to load resource: the server responded with a status of 404 (Not Found)
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/ng2-datepicker
	Error: XHR error (404 Not Found) loading http://localhost:3000/ng2-datepicker
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:3000/ng2-datepicker as "ng2-datepicker" from http://localhost:3000/app/app.module.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:154:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:335:33)
	Error loading http://localhost:3000/ng2-datepicker as "ng2-datepicker" from http://localhost:3000/app/app.module.js

i am appreciate that if you can help me and reply soon

**Comment by jkuri** [comment]
hi. you need to configure SystemJS configuration to pick up `ng2-datepicker.js` correctly.

**Comment by deshazer72** [comment]
@jkuri  I used angular2 quick start I do not have System.js I have systemjs.config.js and I added 'ng2-datepicker': 'npm:ng2-datepicker', and i still get this error am I missing something?

**Comment by deshazer72** [comment]
@jkuri  it appears that this is trying to use localhost:3000 where my app is running ng-datepicker. where everything else in systemjs.config.js is using zone.js is there supposed to be a <script include in index.html

**Comment by jkuri** [comment]
@deshazer72 whenever you get 404 error by SystemJS you can be pretty sure that your configuration is not okay.

**Comment by deshazer72** [comment]
@jkuri  i followed your guide on your page I put the css in index.html i did the npm install that worked fine I am not getting errors when i do the import but after i save it throws those errors I have no idea what I am missing. So then i tried googling and looking to see what people done and that is when they said they had to add the ng2-datepicker into system.js which I figured my systemjs.config.js is the same thing so i tried that. Still getting the same errors

**Comment by deshazer72** [comment]
@jkuri I fixed my issue I am going to post it here so if anyone else has the issue they can fix it easily. I had to npm install moment and ng2-slimscroll after that I had to add ng2-datepicker, moment, and ng2-slimscroall tp my paths map app in systemjs.config.js. 

'ng2-datepicker': 'npm:ng2-datepicker', 
      'moment': 'npm:moment', 
      'ng2-slimscroll': 'npm:ng2-slimscroll', 

After I did that I had to add these to my packages 

   packages: {
      'ng2-datepicker': {  main: './ng2-datepicker.js', defaultExtension: 'js' },
      'ng2-slimscroll': {  main: './ng2-slimscroll.js', defaultExtension: 'js' },
      'moment': {  main: './moment.js', defaultExtension: 'js' },
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      }
    }
everything is working fine for me hope this helps anyone that is needing it. you can add this to your tutorial read me if you want and update npm. I used angular2 quickstart i do not know if everyone else is using that setup but your datepicker is awesome man.

**Comment by kibbled** [comment]
@deshazer72 your solution didn't work for me, also Quickstart project doesn't seem to even be checked in. How is this even working with systemjs?

**Comment by deshazer72** [comment]
@kibbled I downloaded angular quickstart from git hub if you send me your email I will send you all of my configuration and screenshots that it is working in both chrome and IE

**Comment by deshazer72** [comment]
@kibbled  if you just want to email me my email is tiger72.jd@gmail.com and I will email you back 

![image](https://cloud.githubusercontent.com/assets/20157793/21809599/0f289c40-d70e-11e6-8679-37fbd97cb41e.png)

**Comment by deshazer72** [comment]
here is my system config 

![image](https://cloud.githubusercontent.com/assets/20157793/21809809/e18ea152-d70e-11e6-8e5f-48dda20643b0.png)

this is my module.ts 

![image](https://cloud.githubusercontent.com/assets/20157793/21809836/02ec3472-d70f-11e6-8d13-52692e1a9241.png)

this is my variables in my component 

![image](https://cloud.githubusercontent.com/assets/20157793/21809867/22e379ac-d70f-11e6-8be4-4384e1602991.png)

then this is my html 

![image](https://cloud.githubusercontent.com/assets/20157793/21809902/4632db78-d70f-11e6-91a5-9f2046155820.png)

notice I did have to use ngmodeloptions and in my modules I had to import custom elements schema... in order for all of this to work. I hope this puts you in the right direction. I have now implemented this on several projects that I had going ... I know this with systemconfig works fine.

**Comment by deshazer72** [comment]
@kibbled  hey for some reason I am having trouble seeing your screen shots through email. where I work blocks gmail so I am currently unable  to just make sure its not my network I am on. but you said the calendar was missing so one key thing I left out was make sure you have the css in index.html 

![image](https://cloud.githubusercontent.com/assets/20157793/21820094/f0f24f84-d733-11e6-9f7d-1e1170242119.png)
let me know if this helps
